---
root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - unused-imports
  - import
  - filenames
  - security
env:
  node: true
extends:
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:security/recommended
  - plugin:import/recommended
  - plugin:import/typescript
rules:
  prettier/prettier: error
  semi:
    - error
    - never
  import/order:
    - error
  no-unused-vars: 'off'
  unused-imports/no-unused-vars: error
  unused-imports/no-unused-imports: error
  camelcase: 'off'
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
  comma-spacing: error
  eol-last: error
  indent: 'off'
  keyword-spacing: error
  max-len:
    - warn
    - code: 160
  no-async-promise-executor: 'off'
  no-case-declarations: 'off'
  no-dupe-class-members: 'off'
  no-duplicate-imports:
    - error
    - includeExports: true
  no-multiple-empty-lines:
    - error
    - max: 1
  no-use-before-define: 'off'
  no-trailing-spaces: error
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  object-curly-spacing:
    - error
    - always
  prefer-const: error
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true
  filenames/match-regex:
    - 2
    - '^([a-z.][a-z0-9.]*)(-[a-z0-9.]+)*|^[a-z]{2}-[A-Z]{2}$'
    - false
  'import/no-deprecated': 'warn'
  'import/no-extraneous-dependencies': error
  complexity: ['error', 12]
  'security/detect-new-buffer': 'error'
  'security/detect-unsafe-regex': 'error'
  '@typescript-eslint/explicit-module-boundary-types': ['error']
  '@typescript-eslint/naming-convention':
    - warn
    - selector: variableLike
      format:
        - camelCase
    - selector: variable
      modifiers:
        - const
      format:
        - camelCase
        - UPPER_CASE
    - selector: interface
      format:
        - PascalCase
      custom:
        regex: '^(I[A-Z]|_I[A-Z])'
        match: false
    - selector: typeLike
      format:
        - PascalCase
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
      paths:
        - /usr/local/share/global_modules
      moduleDirectory:
        - node_modules
