---
version: '3.9'
services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'pnpm run test'
  compile:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'pnpm run compile'
  lint:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'pnpm run lint'
