---
version: '3.9'
services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'yarn test'
  compile:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'yarn compile'
  lint:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 'yarn lint'
