---
name: GitHub Actions Demo
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build docker image
        id: docker_build
        run: |
          docker-compose -f docker/docker-compose.yml build
          docker-compose -f docker/docker-compose.yml run --rm build
          docker-compose -f docker/docker-compose.yml run --rm lint
          docker-compose -f docker/docker-compose.yml run --rm lint-yaml
          docker-compose -f docker/docker-compose.yml run --rm test
